spring:
  datasource:
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariConnectionPool
      minimum-idle: 3
      maximum-pool-size: 100
      idle-timeout: 250000 # db설정확인 후 세팅 필요
      max-lifetime: 290000 # db설정확인 후 세팅 필요
      validation-timeout: 10000 # db설정확인 후 세팅 필요
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        useSSL: false
        useUnicode: yes
        characterEncoding: UTF-8
        serverTimezone: Asia/Seoul
        autoReconnection: true
        allowMultiQueries: true
  jpa:
    hibernate.ddl-auto: none # 절대 건들지 말 것. ( 데이터 다 삭제될 수 있음. )
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          Charset: utf-8
          useUnicode: true
        default_batch_fetch_size: 100
        jdbc.lob.non_contextual_creation: true