### Profile ###
# Profile 값에 따라 외부파일 Import 함.

## local ##
spring:
  config:
    activate:
      on-profile: local
    import:
      - file:${app.config-path}/web/application-local.yml

---
## dev ##
spring:
  config:
    activate:
      on-profile: dev
    import:
      - file:${app.config-path}/web/application-dev.yml

---
## prod1 ##
spring:
  config:
    activate:
      on-profile: prod1
    import:
      - file:${app.config-path}/web/application-prod1.yml

---
## prod2 ##
spring:
  config:
    activate:
      on-profile: prod2
    import:
      - file:${app.config-path}/web/application-prod2.yml

---
## test ##
spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:application-test.yml
