### test ###
# 테스트에 사용할 H2 DB 설정. ( Memory DB )
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true