server:
  address: 127.0.0.1
  port: 8084
  http2:
    enabled: false
  compression:
    enabled: true
    mime-types: application/json
  servlet:
    application-display-name: ${app.name}-API
    contextPath: /api

spring:
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-profile.yml
      #- optional:classpath:application-actuator.yml
  servlet:
    multipart:
      max-file-size: 50MB
  messages:
    basename: messages/message
    encoding: UTF-8

app:
  name: BLOG
  default-path: c:/app/${app.name}
  config-path: ${app.default-path}/config
  upload-path: ${app.default-path}/upload

logging:
  file:
    path: ${app.default-path}/api/logs
    name: ${logging.file.path}/app.log