### Profile ###
# Profile 값에 따라 외부파일 Import 함.

## local ##
spring:
  config:
    activate:
      on-profile: prod
    import:
      - file:${app.config-path}/application-prod.yml

---
## test ##
spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:application-test.yml
