
server:
  address: 127.0.0.1
  port: 8084
  http2:
    enabled: false # HTTP2 \uC0AC\uC6A9 \uC5EC\uBD80. \uC0AC\uC6A9\uC2DC SSL(TLS) \uD544\uC218.

  compression:
    enabled: true # \uC751\uB2F5 \uB370\uC774\uD130 \uC555\uCD95 \uC5EC\uBD80.
    mime-types: application/json,text/html,text/css,application/javascript
  servlet:
    application-display-name: API_SERVER

### \uC2A4\uD504\uB9C1 \uC124\uC815 ###
spring:
  config:
    import:
      - classpath:application-db.yml                  # DB \uAE30\uBCF8 \uC124\uC815.
      - classpath:application-profile.yml             # profile\uC5D0 \uB530\uB77C \uC678\uBD80 \uC124\uC815 \uD30C\uC77C \uAC00\uC838\uC634.
      ##- optional:classpath:application-actuator.yml   # actuator \uC124\uC815.( optional )
  servlet:
    multipart:
      max-file-size: 50MB # multipart \uC6A9\uB7C9 \uC81C\uD55C.
  messages:
    basename: messages/message
    encoding: UTF-8

app:
  name: BLOG
  default-path: /app/${app.name}
  config-path: ${app.default-path}/api/config
  upload-path: ${app.default-path}/upload

logging:
  file:
    path: ${app.default-path}/logs/api # \uB85C\uADF8 \uC800\uC7A5 \uC704\uCE58.
    name: ${logging.file.path}/api.log # Spring Boot Admin \uC5D0\uC11C \uC870\uD68C\uD560 \uB85C\uADF8\uD30C\uC77C.